chore: add instruction for migrate JupyterLab Classic to Current
ibm-skills-network/author-workbench-knowledgebase pull request #50
Opened 2024-03-08 18:00 UTC by Ericc-Hao

2024-03-13 20:59 UTC, ElioDiNino requested changes

2024-03-13 20:59 UTC, ElioDiNino commented on docs/labs/jupyterlab-filelibrary.md
> +# Acess File Library within Author Workbench
```suggestion
# Access File Library within Author Workbench
```

2024-03-13 20:59 UTC, ElioDiNino commented on docs/labs/jupyterlab-filelibrary.md
> +1. **Open Your Lab:** Begin by launching your lab detail page.
```suggestion
1. **Open Your Lab:** Begin by clicking on your lab in Author Workbench to view its details page.
```

2024-03-13 20:59 UTC, ElioDiNino commented on docs/labs/jupyterlab-filelibrary.md
> +2. **Locate the Content Tab:** In the lab, find and click on the "Content" Tab. Refer to the image below for guidance:
```suggestion
2. **Locate the Content Tab:** In the lab, find and click on the "Content" Tab. Refer to the image below for guidance.
```

2024-03-13 20:59 UTC, ElioDiNino commented on docs/labs/upgrade-jupyterlab.md
> +Follow these steps to upgrade your JupyterLab Classic to JupyterLab Current:
```suggestion
Follow these steps to upgrade your JupyterLab Classic lab to JupyterLab Current:
```

2024-03-13 20:59 UTC, ElioDiNino commented on docs/labs/upgrade-jupyterlab.md
> +1. **Open Your Lab:** Begin by launching your lab detail page.
```suggestion
1. **Open Your Lab:** Begin by clicking on your lab in Author Workbench to view its details page.
```

2024-03-13 20:59 UTC, ElioDiNino commented on docs/labs/upgrade-jupyterlab.md
> +By completing these steps, your JupyterLab Classic will be successfully updated to the JupyterLab Current.
```suggestion
By completing these steps, your JupyterLab Classic lab will be successfully updated to JupyterLab Current! Please make sure to test your lab after updating and make any necessary adjustments.
```

2024-03-13 20:59 UTC, ElioDiNino commented on docs/skills-network-file-library/how-to-access.md
> +- Directly from Author Workbench on the main page of your Guided Project under `content` tab:
```suggestion
- Directly from Author Workbench on the main page of your Guided Project under the "Content" tab
```

2024-03-13 20:59 UTC, ElioDiNino commented on docs/skills-network-file-library/how-to-access.md
> +- Directly from Author Workbench on the main page of your Course under `content` tab:
```suggestion
- Directly from Author Workbench on the main page of your Course under the "Content" tab
```

2024-03-13 20:59 UTC, ElioDiNino commented on docs/skills-network-file-library/how-to-access.md
>  - Directly from Author IDE when editing your markdown-based instructions:
```suggestion
- Directly from Author IDE when editing your markdown-based instructions
```

2024-03-13 20:59 UTC, ElioDiNino commented on docs/skills-network-file-library/how-to-access.md
> +- Directly from JupyterLab Current or JupyterLite when editing your notebooks:
```suggestion
- Directly from JupyterLab Current or JupyterLite when editing your notebooks
```

2024-03-13 21:07 UTC, ElioDiNino approved these changes
Looks great!

2024-03-14 14:33 UTC, bsteinfeld approved these changes

2024-03-14 14:40 UTC, merged